"""Reproducible choice of which media a batch annotates.

Nothing here touches the database or HTTP. The recorded strategy, seed, and
input fingerprint are exactly what these functions consume, so a stored
selection can be recomputed and compared long after the fact.
"""

import hashlib
import random
from collections.abc import Sequence

RANDOM_STRATEGY = "random"
SEED_BITS = 62


def new_seed() -> int:
    """Return a seed for a new selection.

    The seed is generated by the server rather than supplied by a client: it is
    provenance, not an input a caller may choose.
    """
    return random.SystemRandom().getrandbits(SEED_BITS)


def fingerprint(media_ids: Sequence[str]) -> str:
    """Return a digest identifying the ordered input of a selection.

    Args:
        media_ids: Candidate identifiers, in the deterministic order the
            selection consumed them.

    Returns:
        The lowercase hex digest of that ordered input.
    """
    digest = hashlib.sha256()
    for media_id in media_ids:
        digest.update(media_id.encode())
        digest.update(b"\n")
    return digest.hexdigest()


def choose(media_ids: Sequence[str], size: int, seed: int) -> list[str]:
    """Choose a subset of an ordered candidate list, reproducibly.

    Args:
        media_ids: Candidate identifiers, in a deterministic order.
        size: How many to choose.
        seed: Recorded seed for this selection.

    Returns:
        The chosen identifiers.

    Raises:
        ValueError: When more items are requested than are available.
    """
    if size > len(media_ids):
        raise ValueError("The selection asks for more media than is available.")
    return random.Random(seed).sample(list(media_ids), size)
